### PR TITLE
iOS platform

### PR DESCRIPTION
**Pull request by Jidongang**

### CODE REVIEW

**Comment by ghost** [comment]
does this file include the server code?

**Comment by Jidongang** [comment]
> does this file include the server code?
Nope, the server code hasn't uploaded yet

**Comment by ghost** [comment]
> > does this file include the server code?
> > Nope, the server code hasn't uploaded yet

okay fine 👍

**Comment by lisa2018y** [comment]
good!

**Comment by YingdiSong2019** [comment]
How about the user interface?

**Pull request merged**
