### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by YingdiSong2019**

### CODE REVIEW

**Comment by Xiaoyue-Peng** [comment]
is it the final index.thml?

**Comment by YingdiSong2019** [comment]
> is it the final index.thml?

No, the link between index page and login page doesn't work and the home page's content is also undefined. I am trying to fix the problem of link, and if you guys have some ideas please tell me.

**Comment by YingdiSong2019** [comment]
> > is it the final index.thml?
> 
> No, the link between index page and login page doesn't work and the home page's content is also undefined. I am trying to fix the problem of link, and if you guys have some ideas please tell me.

I fixed this problem just now by rewrite the js file.

**Comment by ghost** [comment]
it looks great, what should we add later?

**Comment by baizheteng** [comment]
does it work now?

**Comment by YingdiSong2019** [comment]
> does it work now?

Yep~

**Comment by YingdiSong2019** [comment]
> it looks great, what should we add later?

Emmm...I have no idea about improvement now, but maybe you guys can  help me.

**Pull request merged**
