### PR TITLE
database ER 

### PR DESCRIPTION
**Pull request by lisa2018y**

### CODE REVIEW

**Comment by YingdiSong2019** [comment]
Why the  relationship between file and err is 'upload'? Is 'have' better?

**Comment by ghost** [comment]
It looks like a file in your code part has something wrong when uploading into git hub. Could you please upload it again?

**Comment by Xiaoyue-Peng** [comment]
I think we shoud add a field about co_user so that only the people related to Synchronous file problem can see the error history

**Comment by Xiaoyue-Peng** [comment]
I mean add a co_user field in err_tb

**Comment by lisa2018y** [comment]
OK，I get that.

**Pull request merged**
