### PR TITLE
delete useless file and upload final report source code draft

### PR DESCRIPTION
**Pull request by ghost**
I decided to upload this source code so that you guys can help me to edit them.

### CODE REVIEW

**Comment by YingdiSong2019** [comment]
I think there should be some details about what's trouble we met when using OT.

**Comment by YingdiSong2019** [comment]
Here is my supplement: 'Firstly, we searched for relevant materials about OT technology from the Internet since our team members are not familiar with this technology. There are various online instructions about OT algorithms using different computer languages such as Java, PHP, and Python.  But unfortunately, the tutorials using swift that our system gonna use are rare. In the process of trying to use OT, although it is easy to understand the principle of this technology, the actual operation is quite complicated. The reason why is that the OT algorithm is dependent on the order, and the different order will lead to different results. In addition, there will be some problem if the original file changed before the modification submit as the modification is based on the old version. Therefore, OT technology did not work well in our system, the bugs always appeared and we even cannot find solutions to solve them.'

**Comment by ghost** [comment]
> I think there should be some details about what's trouble we met when using OT.

Yes make sense, could you please help me to write a little about them more in detail? Thank you soooooooo much：）

**Comment by YingdiSong2019** [comment]
Here is my supplement: 'Firstly, we searched for relevant materials about OT technology from the Internet since our team members are not familiar with this technology. There are various online instructions about OT algorithms using different computer languages such as Java, PHP, and Python. But unfortunately, the tutorials using swift that our system gonna use are rare. In the process of trying to use OT, although it is easy to understand the principle of this technology, the actual operation is quite complicated. The reason why is that the OT algorithm is dependent on the order, and the different order will lead to different results. In addition, there will be some problem if the original file changed before the modification submit as the modification is based on the old version. Therefore, OT technology did not work well in our system, the bugs always appeared and we even cannot find solutions to solve them.'

**Comment by YingdiSong2019** [comment]
> > I think there should be some details about what's trouble we met when using OT.
> 
> Yes make sense, could you please help me to write a little about them more in detail? Thank you soooooooo much：）

Here is my supplement: 'Firstly, we searched for relevant materials about OT technology from the Internet since our team members are not familiar with this technology. There are various online instructions about OT algorithms using different computer languages such as Java, PHP, and Python. But unfortunately, the tutorials using swift that our system gonna use are rare. In the process of trying to use OT, although it is easy to understand the principle of this technology, the actual operation is quite complicated. The reason why is that the OT algorithm is dependent on the order, and the different order will lead to different results. In addition, there will be some problem if the original file changed before the modification submit as the modification is based on the old version. Therefore, OT technology did not work well in our system, the bugs always appeared and we even cannot find solutions to solve them.'

**Comment by baizheteng** [comment]
It is a good idea that you added some necessary explanation!good work!

**Comment by YingdiSong2019** [comment]
Here are some supplement about future work: 'The file table in the database will be encrypted as it can be read directly and malicious tamped when being attacked. We have encrypted the user password with the hash algorithm, but the hash algorithm is irreversible, so we are going to find other encryption algorithms to encrypt the file content. Most of the common encryption methods are one-way and irreversible, we consider to encrypt the content during the transmission process, which means we are going to use protocol encryption like HTTPS.'

**Comment by ghost** [comment]
> > > I think there should be some details about what's trouble we met when using OT.
> > 
> > 
> > Yes make sense, could you please help me to write a little about them more in detail? Thank you soooooooo much：）
> 
> Here is my supplement: 'Firstly, we searched for relevant materials about OT technology from the Internet since our team members are not familiar with this technology. There are various online instructions about OT algorithms using different computer languages such as Java, PHP, and Python. But unfortunately, the tutorials using swift that our system gonna use are rare. In the process of trying to use OT, although it is easy to understand the principle of this technology, the actual operation is quite complicated. The reason why is that the OT algorithm is dependent on the order, and the different order will lead to different results. In addition, there will be some problem if the original file changed before the modification submit as the modification is based on the old version. Therefore, OT technology did not work well in our system, the bugs always appeared and we even cannot find solutions to solve them.'

YOU ARE SOOOOOOOO HELPFUL:)

**Comment by ghost** [comment]
> Here are some supplement about future work: 'The file table in the database will be encrypted as it can be read directly and malicious tamped when being attacked. We have encrypted the user password with the hash algorithm, but the hash algorithm is irreversible, so we are going to find other encryption algorithms to encrypt the file content. Most of the common encryption methods are one-way and irreversible, we consider to encrypt the content during the transmission process, which means we are going to use protocol encryption like HTTPS.'

make sense ! I will add them into latex draft

**Pull request merged**
