### PR TITLE
The brief evaluation of database

### PR DESCRIPTION
**Pull request by YingdiSong2019**

### CODE REVIEW

**Comment by ghost** [comment]
Have you ever done the file content？Could I add this part to latex?

**Comment by baizheteng** [comment]
Can you explain the detail more concrete?like...emmm...the problems that why we create these tables?

**Comment by YingdiSong2019** [comment]
- [ ] 

> Have you ever done the file content？Could I add this part to latex?

Of course you can.

**Comment by YingdiSong2019** [comment]
> Can you explain the detail more concrete?like...emmm...the problems that why we create these tables?
 
The details are in the design part.

**Pull request merged**
