### PR TITLE
simplest unit test with thinkphp

### PR DESCRIPTION
**Pull request by ghost**
please add the unit test to a new fold, and named this folder as "test" :)

### CODE REVIEW

**Comment by baizheteng** [comment]
is this unit testing for our whole project?

**Comment by baizheteng** [comment]
> is this unit testing for our whole project?

no, just for testing our functions by writing in thinkphp

**Comment by ghost** [comment]
> is this unit testing for our whole project?

no, just for checking functions writing with thinkphp

**Comment by lisa2018y** [comment]
What about ios?

**Comment by YingdiSong2019** [comment]
Did you meet any problem?

**Comment by ghost** [comment]
> Did you meet any problem?

yeah...It seems like the unit testing under this version seems to require more system configuration

**Pull request merged**
